name: fsw-donalds
services:
  pg:
    container_name: pg
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fsw-donalds
